### ISSUE TITLE
combine "build" and "history" notebooks

### ISSUE THREAD

**Issue by wjchulme** [opensafely/database-notebooks#35]
The build notebook was designed for users to know what datasets were updated during the latest database build, and the latest event dates that can be trusted for queries using that build. To facilitate the latter we show event counts from the 30 days up to the latest event, and also from Feb 2020 to build date to help contextualise the pattern in the last 30 days. 

In the history notebook we just show events counts per day from the first recorded event to the last. While this doesn't satisfy the original purpose of the build notebook, it's just the showing the same info extended further back in time. So having two separate notebooks seems unnecessary. 

Having 3 graphs side-by-side probably won't work as there's not enough room. So an extra section with the "history" graphs should be enough. Alternatively, spend some time making the graphs interactive (eg with plotly) so you can choose the time period of interest, maybe with quick-access buttons for the 3 time periods (everything, since Feb 2020, last 30 days).

**Comment by iaindillingham** [comment]
This has been done partly by opensafely/tpp-database-history#51 and will be done fully by opensafely/tpp-database-history#55. As work has moved to a new repo, I'm going to close this issue with this comment.
